apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-primary
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=ckkeptnorders keptn_service=frontend keptn_stage=production
            keptn_deployment=primary
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: CONTAINER_IMAGE
          value: robjahn/keptn-orders-front-end:1
        - name: KEPTN_PROJECT
          value: ckkeptnorders
        - name: KEPTN_STAGE
          value: production
        - name: KEPTN_SERVICE
          value: frontend
        - name: KEPTN_DEPLOYMENT
          value: canary
        image: robjahn/keptn-orders-front-end:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        name: frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
status: {}
