apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend-primary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-primary
  type: ClusterIP
status:
  loadBalancer: {}
