apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: frontend
spec:
  gateways:
  - ckkeptnorders-staging-gateway.ckkeptnorders-staging
  - mesh
  hosts:
  - frontend.ckkeptnorders-staging.gke.demo.keptn.sh
  - frontend
  http:
  - route:
    - destination:
        host: frontend.ckkeptnorders-staging.svc.cluster.local
